import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolve } from "node:path";

const sourceUrl = new URL("../src/tokens.json", import.meta.url);
const cssUrl = new URL("../src/tokens.css", import.meta.url);

export async function loadTokens() {
  const source = JSON.parse(await readFile(sourceUrl, "utf8"));
  if (
    !source.version ||
    !source.palette ||
    !Array.isArray(source.groups) ||
    !source.foundations
  ) {
    throw new Error(
      "Token source requires version, palette, groups, and foundations.",
    );
  }
  const values = new Map(Object.entries(source.palette));
  const names = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
  const groupIds = new Set();
  for (const group of source.groups) {
    if (
      !names.test(group.id) ||
      groupIds.has(group.id) ||
      !group.title ||
      !group.description ||
      !Array.isArray(group.tokens)
    ) {
      throw new Error(`Invalid or duplicate token group: ${group.id}`);
    }
    groupIds.add(group.id);
    for (const token of group.tokens) {
      if (values.has(token.name))
        throw new Error(`Duplicate token name: ${token.name}`);
      if (!token.description)
        throw new Error(`Missing description for ${token.name}`);
      values.set(token.name, token.value);
    }
  }
  const resolved = new Map();
  function resolveToken(name, ancestors = []) {
    if (resolved.has(name)) return resolved.get(name);
    if (!values.has(name)) throw new Error(`Unknown token reference: ${name}`);
    if (!names.test(name)) throw new Error(`Invalid token name: ${name}`);
    if (ancestors.includes(name))
      throw new Error(
        `Circular token reference: ${[...ancestors, name].join(" → ")}`,
      );
    const raw = values.get(name);
    if (typeof raw !== "string")
      throw new Error(`Invalid token value: ${name}`);
    const reference = raw.match(/^\{([a-z0-9-]+)\}$/);
    const value = reference
      ? resolveToken(reference[1], [...ancestors, name])
      : raw;
    if (!/^#[\da-f]{6}(?:[\da-f]{2})?$/i.test(value))
      throw new Error(`Invalid hex colour for ${name}: ${value}`);
    resolved.set(name, value.toLowerCase());
    return value.toLowerCase();
  }
  for (const name of values.keys()) resolveToken(name);
  const foundations = source.foundations;
  if (
    !Array.isArray(foundations.spacing) ||
    !foundations.spacing.every(
      (value, index, items) =>
        Number.isInteger(value) &&
        value >= 0 &&
        value % 4 === 0 &&
        (!index || value > items[index - 1]),
    )
  ) {
    throw new Error(
      "Spacing must be an ascending unique scale of nonnegative 4px increments.",
    );
  }
  for (const groupName of [
    "radii",
    "controlSizes",
    "typeScale",
    "motion",
    "layers",
  ]) {
    const group = foundations[groupName];
    if (!group || typeof group !== "object" || Array.isArray(group))
      throw new Error(`Missing foundation group: ${groupName}`);
    for (const [name, value] of Object.entries(group)) {
      if (!/^[a-z0-9][a-z0-9-]*$/.test(name))
        throw new Error(`Invalid foundation name: ${groupName}.${name}`);
      if (groupName === "layers") {
        if (!Number.isInteger(value) || value < 0)
          throw new Error(`Invalid layer: ${name}`);
      } else if (
        typeof value !== "string" ||
        !/^(?:\d+(?:\.\d+)?(?:px|rem|ms)|cubic-bezier\([\d., -]+\))$/.test(
          value,
        )
      ) {
        throw new Error(`Invalid foundation value: ${groupName}.${name}`);
      }
    }
  }
  return { source, values, resolved };
}

export function generateCSS({ source, values }) {
  const lines = [
    "/* Generated from src/tokens.json. Run npm run tokens:build; do not edit this file. */",
    ":root {",
    "  color-scheme: dark;",
  ];
  for (const [name, value] of values)
    lines.push(`  --${name}: ${value.replace(/^\{(.+)\}$/, "var(--$1)")};`);
  for (const value of source.foundations.spacing)
    lines.push(`  --space-${value}: ${value / 16}rem;`);
  const prefixes = {
    radii: "corner",
    controlSizes: "control",
    typeScale: "type",
    motion: "motion",
    layers: "layer",
  };
  for (const [key, prefix] of Object.entries(prefixes)) {
    for (const [name, value] of Object.entries(source.foundations[key]))
      lines.push(
        `  --${prefix}-${name}: ${typeof value === "string" && value.endsWith("px") ? `${Number.parseFloat(value) / 16}rem` : value};`,
      );
  }
  lines.push("  --radius: var(--corner-md);", "}", "", "@theme inline {");
  for (const name of values.keys())
    lines.push(`  --color-${name}: var(--${name});`);
  for (const name of Object.keys(source.foundations.radii))
    lines.push(`  --radius-${name}: var(--corner-${name});`);
  for (const name of Object.keys(source.foundations.controlSizes))
    lines.push(`  --spacing-control-${name}: var(--control-${name});`);
  for (const name of Object.keys(source.foundations.typeScale))
    lines.push(`  --text-${name}: var(--type-${name});`);
  lines.push("}", "");
  return lines.join("\n");
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  const tokens = await loadTokens();
  const css = generateCSS(tokens);
  if (process.argv.includes("--check")) {
    const current = await readFile(cssUrl, "utf8");
    if (current !== css)
      throw new Error("Generated CSS is stale. Run npm run tokens:build.");
    console.log(`Token CSS is current: ${tokens.values.size} colours.`);
  } else {
    await writeFile(cssUrl, css);
    console.log(
      `Built src/tokens.css: ${tokens.values.size} colours and 6 foundation scales.`,
    );
  }
}
